{"name": "test_broken", "status": "broken", "statusDetails": {"message": "Exception: oops", "trace": "def test_broken():\n>       raise Exception('oops')\nE       Exception: oops\n\ntest_1.py:19: Exception"}, "start": 1609039104654, "stop": 1609039104655, "uuid": "fe591b03-6284-493a-82cc-79d97af78e59", "historyId": "f28efab84f6e3c4573543b6d4dc85443", "testCaseId": "f044a1388deafd44202298a12cf5f881", "fullName": "test_1#test_broken", "labels": [{"name": "suite", "value": "test_1"}, {"name": "host", "value": "PC-20150415WRCK"}, {"name": "thread", "value": "6544-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_1"}]}